#!/usr/bin/env bash

#install Nginx and configure it to listen to port 80 on the server

#install Nginx
sudo apt-get update
sudo apt install nginx

#configur nginx to listen to port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

#Create a file to print Hello World

echo "Hello World!" >> /var/www/html/index.html

#Start the server

sudo service nginix start