#!/usr/bin/env bash

# Update packages and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP'

# Set up custom HTTP response header
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart

